=== rgupta00/springmvc-ymsli/xml_demo/emp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.ymsli.in/emp" 
xmlns:tns="http://www.ymsli.in/emp" 
     elementFormDefault="unqualified">

    <element name="emps" type="tns:emps"></element>

	<complexType name="emps">
		<sequence>
			<element name="ename" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="address" type="string"></element>
			<element name="phone" type="string"></element>
			<element name="email" type="string"></element>
			<element name="dob" type="date"></element>
			<element name="salary" type="double"></element>
			<element name="projects" type="tns:project"
				maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
    </complexType>

    <complexType name="project">
    	<sequence>
    		<element name="pname" type="string"></element>
    		<element name="projmgr" type="string"></element>
    		<element name="startdate" type="date"></element>
    	</sequence>
    </complexType>
</schema>

=== rgupta00/springmvc-ymsli/xml_demo/emp.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:emps xmlns:tns="http://www.ymsli.in/emp" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.ymsli.in/emp emp.xsd ">
  <ename>ename</ename>
  <address>address</address>
  <phone>phone</phone>
  <email>email</email>
  <dob>2001-01-01</dob>
  <salary>0.0</salary>
  <projects>
    <pname>pname</pname>
    <projmgr>projmgr</projmgr>
    <startdate>2001-01-01</startdate>
  </projects>
</tns:emps>
